pipeline {
    agent any
    tools {
        maven 'Maven-3.9.9'  // This name should match what you defined
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivering the package"
            }
        }
    }
}
